abilities = {
    "Arena Trap": {"effect": "cantswitch"},
    "Battle Armor": {"effect": "nocrits"},
    "Blaze": {"effect": "boost_type_if_lowhp:Fire"},
    "Chlorophyll": {"effect": "boost_spe_if_sun"},
    "Clear Body": {"effect": "prevstatreduc"},
    "Cloud Nine": {"effect": "noweather"},
    "Cute Charm": {"effect": "chanceinfatuate"},
    "Damp": {"effect": "noselfkill"},
    "Early Bird": {"effect": "halfsleep"},
    "Effect Spore": {"effect": "chancestatus"},
    "Flame Body": {"effect": "contact_burn"},
    "Flash Fire": {"effect": "Immunity:Fire"},
    "Guts": {"effect": "boost_atk_if_status"},
    "Illuminate": {"effect": "unknown"},
    "Immunity": {"effect": "prevent_status:poisoned"},
    "Inner Focus": {"effect": "noflinch"},
    "Insomnia": {"effect": "nosleep"},
    "Intimidate": {"effect": "on_entry_lower:atk"},
    "Keen Eye": {"effect": "noaccdrop"},
    "Levitate": {"effect": "immunity:Ground"},
    "Lightningrod": {"effect": "immunity:Electric"},
    "Liquid Ooze": {"effect": "unknown"},
    "Marvel Scale": {"effect": "defboost"},
    "Natural Cure": {"effect": "switchstatusdrop"},
    "Oblivious": {"effect": "nolove"},
    "Overgrow": {"effect": "boost_type_if_lowhp:Grass"},
    "Own Tempo": {"effect": "prevent_status:confused"},
    "Poison Point": {"effect": "contact_poison"},
    "Pressure": {"effect": "ppdrop"},
    "Pure Power": {"effect": "doubleattack"},
    "Rain Dish": {"effect": "rainheal"},
    "Rock Head": {"effect": "norecoil"},
    "Run Away": {"effect": "unknown"},
    "Sand Stream": {"effect": "sandstart"},
    "Sand Veil": {"effect": "evasionboost"},
    "Serene Grace": {"effect": "doublesecondary"},
    "Shell Armor": {"effect": "nocrits"},
    "Soundproof": {"effect": "nosoundmoves"},
    "Static": {"effect": "contact_paralyze"},
    "Stench": {"effect": "unknown"},
    "Sticky Hold": {"effect": "nosteal"},
    "Sturdy": {"effect": "1hpsurvive"},
    "Suction Cups": {"effect": "noforceswitch"},
    "Swarm": {"effect": "boost_type_if_lowhp:Bug"},
    "Swift Swim": {"effect": "boost_spe_if_rain"},
    "Synchronize": {"effect": "sharestatus"},
    "Thick Fat": {"effect": "reduceicefire"},
    "Torrent": {"effect": "boost_type_if_lowhp:Water"},
    "Trace": {"effect": "copyability"},
    "Truant": {"effect": "skipeoturn"},
    "Volt Absorb": {"effect": "heal_on_hit:Electric"},
    "Water Absorb": {"effect": "heal_on_hit:Water"},
    "Water Veil": {"effect": "noburn"},
}
