move_types = {
    'Acid Armor': 'Poison', 
    'Aerial Ace': 'Flying', 
    'Agility': 'Psychic', 
    'Air Cutter': 'Flying', 
    'Amnesia': 'Psychic', 
    'AncientPower': 'Rock', 
    'Aromatherapy': 'Grass', 
    'Astonish': 'Ghost', 
    'Attract': 'Normal', 
    'Barrier': 'Psychic', 
    'Baton Pass': 'Normal', 
    'Belly Drum': 'Normal', 
    'Bite': 'Dark', 
    'Blaze Kick': 'Fire', 
    'Blizzard': 'Ice', 
    'Block': 'Normal', 
    'Body Slam': 'Normal', 
    'Bonemerang': 'Ground', 
    'Bounce': 'Flying', 
    'Brick Break': 'Fighting', 
    'Bulk Up': 'Fighting', 
    'Calm Mind': 'Psychic', 
    'Charm': 'Normal', 
    'Confuse Ray': 'Ghost', 
    'Cosmic Power': 'Psychic', 
    'Counter': 'Fighting', 
    'Cross Chop': 'Fighting', 
    'Crunch': 'Dark', 
    'Crush Claw': 'Normal', 
    'Curse': 'Normal', 
    'Defense Curl': 'Normal', 
    'Destiny Bond': '', 
    'Detect': 'Fighting', 
    'Dig': 'Ground', 
    'Disable': 'Normal', 
    'Dive': 'Water', 
    'Dizzy Punch': 'Normal', 
    'Double Kick': 'Fighting', 
    'Double Team': 'Normal', 
    'Double-Edge': 'Normal', 
    'Dragon Claw': 'Dragon', 
    'Dragon Dance': 'Dragon', 
    'DragonBreath': 'Dragon', 
    'Dream Eater': 'Psychic', 
    'Drill Peck': 'Flying', 
    'DynamicPunch': 'Fighting', 
    'Earthquake': 'Ground', 
    'Encore': 'Normal', 
    'Endure': 'Normal', 
    'Explosion': 'Normal', 
    'Extrasensory': 'Psychic', 
    'ExtremeSpeed': 'Normal', 
    'Facade': 'Normal', 
    'Faint Attack': 'Dark', 
    'Fake Out': 'Normal', 
    'Fake Tears': 'Dark', 
    'Fire Blast': 'Fire', 
    'Fire Punch': 'Fire', 
    'Fissure': 'Ground', 
    'Flail': 'Normal', 
    'Flamethrower': 'Fire', 
    'Flash': 'Normal', 
    'Fly': 'Flying', 
    'Focus Punch': 'Psychic', 
    'Follow Me': 'Normal', 
    'Frustration': 'Normal', 
    'Future Sight': '', 
    'Giga Drain': 'Grass', 
    'GrassWhistle': 'Grass', 
    'Grudge': 'Ghost', 
    'Hail': 'Ice', 
    'Headbutt': 'Normal', 
    'Heat Wave': 'Fire', 
    'Hi Jump Kick': 'Fighting', 
    'Horn Drill': 'Normal', 
    'Hydro Pump': 'Water', 
    'Hyper Beam': 'Normal', 
    'Hyper Voice': 'Normal', 
    'Hypnosis': 'Psychic', 
    'Ice Beam': 'Ice', 
    'Ice Punch': 'Ice', 
    'Icy Wind': 'Ice', 
    'Ingrain': 'Grass', 
    'Iron Tail': 'Steel', 
    'Knock Off': 'Dark', 
    'Leaf Blade': 'Grass', 
    'Leech Seed': 'Grass', 
    'Light Screen': 'Psychic', 
    'Lovely Kiss': 'Normal', 
    'Luster Purge': 'Psychic', 
    'Mach Punch': 'Fighting', 
    'Magical Leaf': 'Grass', 
    'Mean Look': 'Normal', 
    'Mega Kick': 'Normal', 
    'Megahorn': 'Bug', 
    'Memento': 'Dark', 
    'Metal Claw': 'Steel', 
    'Meteor Mash': 'Steel', 
    'Metronome': 'Normal', 
    'Milk Drink': 'Normal', 
    'Minimize': 'Normal', 
    'Mirror Coat': 'Psychic', 
    'Mist Ball': 'Psychic', 
    'Moonlight': 'Normal', 
    'Mud-Slap': 'Ground', 
    'Night Shade': 'Ghost', 
    'Nightmare': 'Ghost', 
    'Outrage': 'Dragon', 
    'Overheat': 'Fire', 
    'Pain Split': 'Normal', 
    'Perish Song': 'Normal', 
    'Petal Dance': 'Grass', 
    'Protect': 'Normal', 
    'Psych Up': 'Normal', 
    'Psychic': 'Psychic', 
    'Pursuit': 'Dark', 
    'Quick Attack': 'Normal', 
    'Rain Dance': 'Water', 
    'Recover': 'Normal', 
    'Reflect': 'Psychic', 
    'Refresh': 'Normal', 
    'Rest': 'Normal', 
    'Return': 'Normal', 
    'Revenge': 'Fighting', 
    'Reversal': 'Fighting', 
    'Roar': 'Normal', 
    'Rock Slide': 'Rock', 
    'Rock Tomb': 'Rock', 
    'Rollout': 'Rock', 
    'Safeguard': 'Normal', 
    'Sand Tomb': 'Ground', 
    'Sand-Attack': 'Ground', 
    'Sandstorm': 'Rock', 
    'Scary Face': 'Normal', 
    'Screech': 'Normal', 
    'Secret Power': 'Normal', 
    'Seismic Toss': 'Fighting', 
    'Shadow Ball': 'Ghost', 
    'Sheer Cold': 'Ice', 
    'Signal Beam': 'Bug', 
    'Silver Wind': 'Bug', 
    'Sing': 'Normal', 
    'Skill Swap': 'Psychic', 
    'Sky Attack': 'Flying', 
    'Sky Uppercut': 'Fighting', 
    'Slash': 'Normal', 
    'Sleep Powder': 'Grass', 
    'Sleep Talk': 'Normal', 
    'Sludge Bomb': 'Poison', 
    'SmellingSalt': 'Normal', 
    'SmokeScreen': 'Normal', 
    'Softboiled': 'Normal', 
    'SolarBeam': 'Grass', 
    'Spark': 'Electric', 
    'Spikes': 'Ground', 
    'Spore': 'Grass', 
    'Steel Wing': 'Steel', 
    'Stun Spore': 'Grass', 
    'Substitute': 'Normal', 
    'Sunny Day': 'Fire', 
    'Superpower': 'Fighting', 
    'Surf': 'Water', 
    'Swagger': 'Normal', 
    'Sweet Scent': 'Normal', 
    'Swift': 'Normal', 
    'Swords Dance': 'Normal', 
    'Synthesis': 'Grass', 
    'Thrash': 'Normal', 
    'Thunder': 'Electric', 
    'Thunder Wave': 'Electric', 
    'ThunderPunch': 'Electric', 
    'Thunderbolt': 'Electric', 
    'Torment': 'Dark', 
    'Toxic': 'Poison', 
    'Tri Attack': 'Normal', 
    'Trick': 'Psychic', 
    'Water Pulse': 'Water', 
    'Will-O-Wisp': 'Fire', 
    'Wish': 'Normal', 
    'Wrap': 'Normal', 
    'Yawn': 'Normal', 
    'Zap Cannon': 'Electric', 
}
