move_types = {
    'Acid Armor': {'type': 'Poison', 'category': 'Status', 'effect': 'def_up'},
    'Aerial Ace': {'type': 'Flying', 'category': 'Physical', 'effect': '', 'power': 60},
    'Agility': {'type': 'Psychic', 'category': 'Status', 'effect': 'spe_up'},
    'Air Cutter': {'type': 'Flying', 'category': 'Physical', 'effect': '', 'power': 60},
    'Amnesia': {'type': 'Psychic', 'category': 'Status', 'effect': 'spd_up'},
    'AncientPower': {'type': 'Rock', 'category': 'Physical', 'effect': ''},
    'Aromatherapy': {'type': 'Grass', 'category': 'Physical', 'effect': ''},
    'Astonish': {'type': 'Ghost', 'category': 'Physical', 'effect': '', 'power': 30},
    'Attract': {'type': 'Normal', 'category': 'Status', 'effect': 'infatuate'},
    'Barrier': {'type': 'Psychic', 'category': 'Physical', 'effect': ''},
    'Baton Pass': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Belly Drum': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Bite': {'type': 'Dark', 'category': 'Physical', 'effect': '', 'power': 60},
    'Blaze Kick': {'type': 'Fire', 'category': 'Physical', 'effect': '', 'power': 85},
    'Blizzard': {'type': 'Ice', 'category': 'Physical', 'effect': '', 'power': 110},
    'Block': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Body Slam': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 85},
    'Bonemerang': {'type': 'Ground', 'category': 'Physical', 'effect': '', 'power': 50},
    'Bounce': {'type': 'Flying', 'category': 'Physical', 'effect': '', 'power': 85},
    'Brick Break': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 75},
    'Bulk Up': {'type': 'Fighting', 'category': 'Status', 'effect': 'atk_def_up'},
    'Calm Mind': {'type': 'Psychic', 'category': 'Status', 'effect': 'spa_spd_up'},
    'Charm': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Confuse Ray': {'type': 'Ghost', 'category': 'Status', 'effect': 'confuse'},
    'Cosmic Power': {'type': 'Psychic', 'category': 'Physical', 'effect': ''},
    'Counter': {'type': 'Fighting', 'category': 'Physical', 'effect': ''},
    'Cross Chop': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 100},
    'Crunch': {'type': 'Dark', 'category': 'Physical', 'effect': '', 'power': 80},
    'Crush Claw': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 75},
    'Curse': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Defense Curl': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Destiny Bond': {'type': 'nan', 'category': 'Physical', 'effect': ''},
    'Detect': {'type': 'Fighting', 'category': 'Physical', 'effect': ''},
    'Dig': {'type': 'Ground', 'category': 'Physical', 'effect': '', 'power': 80},
    'Disable': {'type': 'Normal', 'category': 'Status', 'effect': 'disable'},
    'Dive': {'type': 'Water', 'category': 'Physical', 'effect': '', 'power': 80},
    'Dizzy Punch': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 70},
    'Double Kick': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 30},
    'Double Team': {'type': 'Normal', 'category': 'Status', 'effect': 'eva_up'},
    'Double-Edge': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Dragon Claw': {'type': 'Dragon', 'category': 'Physical', 'effect': '', 'power': 80},
    'Dragon Dance': {'type': 'Dragon', 'category': 'Status', 'effect': 'atk_spe_up'},
    'DragonBreath': {'type': 'Dragon', 'category': 'Physical', 'effect': ''},
    'Dream Eater': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'power': 100},
    'Drill Peck': {'type': 'Flying', 'category': 'Physical', 'effect': '', 'power': 80},
    'DynamicPunch': {'type': 'Fighting', 'category': 'Physical', 'effect': ''},
    'Earthquake': {'type': 'Ground', 'category': 'Physical', 'effect': '', 'power': 100},
    'Encore': {'type': 'Normal', 'category': 'Status', 'effect': 'encore'},
    'Endure': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Explosion': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 250},
    'Extrasensory': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'power': 80},
    'ExtremeSpeed': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Facade': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 70},
    'Faint Attack': {'type': 'Dark', 'category': 'Physical', 'effect': ''},
    'Fake Out': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 40},
    'Fake Tears': {'type': 'Dark', 'category': 'Physical', 'effect': ''},
    'Fire Blast': {'type': 'Fire', 'category': 'Physical', 'effect': '', 'power': 110},
    'Fire Punch': {'type': 'Fire', 'category': 'Physical', 'effect': '', 'power': 75},
    'Fissure': {'type': 'Ground', 'category': 'Physical', 'effect': ''},
    'Flail': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Flamethrower': {'type': 'Fire', 'category': 'Physical', 'effect': '', 'power': 90},
    'Flash': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Fly': {'type': 'Flying', 'category': 'Physical', 'effect': '', 'power': 90},
    'Focus Punch': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'power': 150},
    'Follow Me': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Frustration': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Future Sight': {'type': 'nan', 'category': 'Physical', 'effect': '', 'power': 120},
    'Giga Drain': {'type': 'Grass', 'category': 'Physical', 'effect': '', 'power': 75},
    'GrassWhistle': {'type': 'Grass', 'category': 'Physical', 'effect': ''},
    'Grudge': {'type': 'Ghost', 'category': 'Physical', 'effect': ''},
    'Hail': {'type': 'Ice', 'category': 'Status', 'effect': 'hail'},
    'Headbutt': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 70},
    'Heat Wave': {'type': 'Fire', 'category': 'Physical', 'effect': '', 'power': 95},
    'Hi Jump Kick': {'type': 'Fighting', 'category': 'Physical', 'effect': ''},
    'Horn Drill': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Hydro Pump': {'type': 'Water', 'category': 'Physical', 'effect': '', 'power': 110},
    'Hyper Beam': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 150},
    'Hyper Voice': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 90},
    'Hypnosis': {'type': 'Psychic', 'category': 'Status', 'effect': 'sleep'},
    'Ice Beam': {'type': 'Ice', 'category': 'Physical', 'effect': '', 'power': 90},
    'Ice Punch': {'type': 'Ice', 'category': 'Physical', 'effect': '', 'power': 75},
    'Icy Wind': {'type': 'Ice', 'category': 'Physical', 'effect': '', 'power': 55},
    'Ingrain': {'type': 'Grass', 'category': 'Physical', 'effect': ''},
    'Iron Tail': {'type': 'Steel', 'category': 'Physical', 'effect': '', 'power': 100},
    'Knock Off': {'type': 'Dark', 'category': 'Physical', 'effect': '', 'power': 65},
    'Leaf Blade': {'type': 'Grass', 'category': 'Physical', 'effect': '', 'power': 90},
    'Leech Seed': {'type': 'Grass', 'category': 'Status', 'effect': 'leech'},
    'Light Screen': {'type': 'Psychic', 'category': 'Status', 'effect': 'spd_wall'},
    'Lovely Kiss': {'type': 'Normal', 'category': 'Status', 'effect': 'sleep'},
    'Luster Purge': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'power': 70},
    'Mach Punch': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 40},
    'Magical Leaf': {'type': 'Grass', 'category': 'Physical', 'effect': '', 'power': 60},
    'Mean Look': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Mega Kick': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 120},
    'Megahorn': {'type': 'Bug', 'category': 'Physical', 'effect': '', 'power': 120},
    'Memento': {'type': 'Dark', 'category': 'Physical', 'effect': ''},
    'Metal Claw': {'type': 'Steel', 'category': 'Physical', 'effect': '', 'power': 50},
    'Meteor Mash': {'type': 'Steel', 'category': 'Physical', 'effect': '', 'power': 90},
    'Metronome': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Milk Drink': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Minimize': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Mirror Coat': {'type': 'Psychic', 'category': 'Physical', 'effect': ''},
    'Mist Ball': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'power': 70},
    'Moonlight': {'type': 'Normal', 'category': 'Status', 'effect': 'heal'},
    'Mud-Slap': {'type': 'Ground', 'category': 'Physical', 'effect': ''},
    'Night Shade': {'type': 'Ghost', 'category': 'Physical', 'effect': ''},
    'Nightmare': {'type': 'Ghost', 'category': 'Physical', 'effect': ''},
    'Outrage': {'type': 'Dragon', 'category': 'Physical', 'effect': '', 'power': 120},
    'Overheat': {'type': 'Fire', 'category': 'Physical', 'effect': '', 'power': 130},
    'Pain Split': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Perish Song': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Petal Dance': {'type': 'Grass', 'category': 'Physical', 'effect': '', 'power': 120},
    'Protect': {'type': 'Normal', 'category': 'Status', 'effect': 'protect'},
    'Psych Up': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Psychic': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'power': 90},
    'Pursuit': {'type': 'Dark', 'category': 'Physical', 'effect': '', 'power': 40},
    'Quick Attack': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 40},
    'Rain Dance': {'type': 'Water', 'category': 'Status', 'effect': 'rain'},
    'Recover': {'type': 'Normal', 'category': 'Status', 'effect': 'heal'},
    'Reflect': {'type': 'Psychic', 'category': 'Status', 'effect': 'def_wall'},
    'Refresh': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Rest': {'type': 'Normal', 'category': 'Status', 'effect': 'heal'},
    'Return': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Revenge': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 60},
    'Reversal': {'type': 'Fighting', 'category': 'Physical', 'effect': ''},
    'Roar': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Rock Slide': {'type': 'Rock', 'category': 'Physical', 'effect': '', 'power': 75},
    'Rock Tomb': {'type': 'Rock', 'category': 'Physical', 'effect': '', 'power': 60},
    'Rollout': {'type': 'Rock', 'category': 'Physical', 'effect': '', 'power': 30},
    'Safeguard': {'type': 'Normal', 'category': 'Status', 'effect': 'status_block'},
    'Sand Tomb': {'type': 'Ground', 'category': 'Physical', 'effect': '', 'power': 35},
    'Sand-Attack': {'type': 'Ground', 'category': 'Physical', 'effect': ''},
    'Sandstorm': {'type': 'Rock', 'category': 'Status', 'effect': 'sandstorm'},
    'Scary Face': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Screech': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Secret Power': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 70},
    'Seismic Toss': {'type': 'Fighting', 'category': 'Physical', 'effect': ''},
    'Shadow Ball': {'type': 'Ghost', 'category': 'Physical', 'effect': '', 'power': 80},
    'Sheer Cold': {'type': 'Ice', 'category': 'Physical', 'effect': ''},
    'Signal Beam': {'type': 'Bug', 'category': 'Physical', 'effect': '', 'power': 75},
    'Silver Wind': {'type': 'Bug', 'category': 'Physical', 'effect': '', 'power': 60},
    'Sing': {'type': 'Normal', 'category': 'Status', 'effect': 'sleep'},
    'Skill Swap': {'type': 'Psychic', 'category': 'Physical', 'effect': ''},
    'Sky Attack': {'type': 'Flying', 'category': 'Physical', 'effect': '', 'power': 140},
    'Sky Uppercut': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 85},
    'Slash': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 70},
    'Sleep Powder': {'type': 'Grass', 'category': 'Status', 'effect': 'sleep'},
    'Sleep Talk': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Sludge Bomb': {'type': 'Poison', 'category': 'Physical', 'effect': '', 'power': 90},
    'SmellingSalt': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'SmokeScreen': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Softboiled': {'type': 'Normal', 'category': 'Status', 'effect': 'heal'},
    'SolarBeam': {'type': 'Grass', 'category': 'Physical', 'effect': ''},
    'Spark': {'type': 'Electric', 'category': 'Physical', 'effect': '', 'power': 65},
    'Spikes': {'type': 'Ground', 'category': 'Physical', 'effect': ''},
    'Spore': {'type': 'Grass', 'category': 'Status', 'effect': 'sleep'},
    'Steel Wing': {'type': 'Steel', 'category': 'Physical', 'effect': '', 'power': 70},
    'Stun Spore': {'type': 'Grass', 'category': 'Physical', 'effect': ''},
    'Substitute': {'type': 'Normal', 'category': 'Status', 'effect': 'substitute'},
    'Sunny Day': {'type': 'Fire', 'category': 'Status', 'effect': 'sun'},
    'Superpower': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 120},
    'Surf': {'type': 'Water', 'category': 'Physical', 'effect': '', 'power': 90},
    'Swagger': {'type': 'Normal', 'category': 'Status', 'effect': 'confuse'},
    'Sweet Scent': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Swift': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 60},
    'Swords Dance': {'type': 'Normal', 'category': 'Status', 'effect': 'atk_up'},
    'Synthesis': {'type': 'Grass', 'category': 'Status', 'effect': 'heal'},
    'Thrash': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 120},
    'Thunder': {'type': 'Electric', 'category': 'Physical', 'effect': '', 'power': 110},
    'Thunder Wave': {'type': 'Electric', 'category': 'Status', 'effect': 'paralyze'},
    'ThunderPunch': {'type': 'Electric', 'category': 'Physical', 'effect': ''},
    'Thunderbolt': {'type': 'Electric', 'category': 'Physical', 'effect': '', 'power': 90},
    'Torment': {'type': 'Dark', 'category': 'Physical', 'effect': ''},
    'Toxic': {'type': 'Poison', 'category': 'Status', 'effect': 'toxic'},
    'Tri Attack': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 80},
    'Trick': {'type': 'Psychic', 'category': 'Physical', 'effect': ''},
    'Water Pulse': {'type': 'Water', 'category': 'Physical', 'effect': '', 'power': 60},
    'Will-O-Wisp': {'type': 'Fire', 'category': 'Status', 'effect': 'burn'},
    'Wish': {'type': 'Normal', 'category': 'Physical', 'effect': ''},
    'Wrap': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 15},
    'Yawn': {'type': 'Normal', 'category': 'Status', 'effect': 'sleep_next_turn'},
    'Zap Cannon': {'type': 'Electric', 'category': 'Physical', 'effect': '', 'power': 120},
}