move_types = {
    'Acid Armor': {'type': 'Poison', 'category': 'Status', 'effect': 'def_up', 'accuracy': 100},
    'Aerial Ace': {'type': 'Flying', 'category': 'Physical', 'effect': '', 'power': 60, 'accuracy': 100},
    'Agility': {'type': 'Psychic', 'category': 'Status', 'effect': 'spe_up', 'accuracy': 100},
    'Air Cutter': {'type': 'Flying', 'category': 'Physical', 'effect': '', 'power': 60, 'accuracy': 95, 'status': 'crit_boost', 'status_chance': 100},
    'Amnesia': {'type': 'Psychic', 'category': 'Status', 'effect': 'spd_up', 'accuracy': 100},
    'AncientPower': {'type': 'Rock', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Aromatherapy': {'type': 'Grass', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Astonish': {'type': 'Ghost', 'category': 'Physical', 'effect': '', 'power': 30, 'accuracy': 100},
    'Attract': {'type': 'Normal', 'category': 'Status', 'effect': 'infatuate', 'accuracy': 100},
    'Barrier': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Baton Pass': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Belly Drum': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Bite': {'type': 'Dark', 'category': 'Physical', 'effect': '', 'power': 60, 'accuracy': 100},
    'Blaze Kick': {'type': 'Fire', 'category': 'Physical', 'effect': '', 'power': 85, 'accuracy': 100},
    'Blizzard': {'type': 'Ice', 'category': 'Physical', 'effect': '', 'power': 110, 'accuracy': 70},
    'Block': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Body Slam': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 85, 'accuracy': 100, 'status': 'paralyzed', 'status_chance': 30},
    'Bonemerang': {'type': 'Ground', 'category': 'Physical', 'effect': '', 'power': 50, 'accuracy': 100},
    'Bounce': {'type': 'Flying', 'category': 'Physical', 'effect': '', 'power': 85, 'accuracy': 100},
    'Brick Break': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 75, 'accuracy': 100},
    'Bulk Up': {'type': 'Fighting', 'category': 'Status', 'effect': 'atk_def_up', 'accuracy': 100},
    'Calm Mind': {'type': 'Psychic', 'category': 'Status', 'effect': 'spa_spd_up', 'accuracy': 100},
    'Charm': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Confuse Ray': {'type': 'Ghost', 'category': 'Status', 'effect': 'confuse', 'accuracy': 100},
    'Cosmic Power': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Counter': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Cross Chop': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 100, 'accuracy': 80},
    'Crunch': {'type': 'Dark', 'category': 'Physical', 'effect': '', 'power': 80, 'accuracy': 100},
    'Crush Claw': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 75, 'accuracy': 100},
    'Curse': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Defense Curl': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Destiny Bond': {'type': 'nan', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Detect': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Dig': {'type': 'Ground', 'category': 'Physical', 'effect': '', 'power': 80, 'accuracy': 100},
    'Disable': {'type': 'Normal', 'category': 'Status', 'effect': 'disable', 'accuracy': 100},
    'Dive': {'type': 'Water', 'category': 'Physical', 'effect': '', 'power': 80, 'accuracy': 100},
    'Dizzy Punch': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 70, 'accuracy': 100},
    'Double Kick': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 30, 'accuracy': 100},
    'Double Team': {'type': 'Normal', 'category': 'Status', 'effect': 'eva_up', 'accuracy': 100},
    'Double-Edge': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Dragon Claw': {'type': 'Dragon', 'category': 'Physical', 'effect': '', 'power': 80, 'accuracy': 100},
    'Dragon Dance': {'type': 'Dragon', 'category': 'Status', 'effect': 'atk_spe_up', 'accuracy': 100},
    'DragonBreath': {'type': 'Dragon', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Dream Eater': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'power': 100, 'accuracy': 100},
    'Drill Peck': {'type': 'Flying', 'category': 'Physical', 'effect': '', 'power': 80, 'accuracy': 100},
    'DynamicPunch': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'accuracy': 50},
    'Earthquake': {'type': 'Ground', 'category': 'Physical', 'effect': '', 'power': 100, 'accuracy': 100},
    'Encore': {'type': 'Normal', 'category': 'Status', 'effect': 'encore', 'accuracy': 100},
    'Endure': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Explosion': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 250, 'accuracy': 100},
    'Extrasensory': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'power': 80, 'accuracy': 100},
    'ExtremeSpeed': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Facade': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 70, 'accuracy': 100},
    'Faint Attack': {'type': 'Dark', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Fake Out': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 40, 'accuracy': 100, 'status': 'flinch', 'status_chance': 100},
    'Fake Tears': {'type': 'Dark', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Fire Blast': {'type': 'Fire', 'category': 'Physical', 'effect': '', 'power': 110, 'accuracy': 85, 'status': 'burned', 'status_chance': 10},
    'Fire Punch': {'type': 'Fire', 'category': 'Physical', 'effect': '', 'power': 75, 'accuracy': 100},
    'Fissure': {'type': 'Ground', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Flail': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Flamethrower': {'type': 'Fire', 'category': 'Physical', 'effect': '', 'power': 90, 'accuracy': 100, 'status': 'burned', 'status_chance': 10},
    'Flash': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Fly': {'type': 'Flying', 'category': 'Physical', 'effect': '', 'power': 90, 'accuracy': 100},
    'Focus Punch': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'power': 150, 'accuracy': 100},
    'Follow Me': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Frustration': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Future Sight': {'type': 'nan', 'category': 'Physical', 'effect': '', 'power': 120, 'accuracy': 100},
    'Giga Drain': {'type': 'Grass', 'category': 'Physical', 'effect': '', 'power': 75, 'accuracy': 100},
    'GrassWhistle': {'type': 'Grass', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Grudge': {'type': 'Ghost', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Hail': {'type': 'Ice', 'category': 'Status', 'effect': 'hail', 'accuracy': 100},
    'Headbutt': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 70, 'accuracy': 100},
    'Heat Wave': {'type': 'Fire', 'category': 'Physical', 'effect': '', 'power': 95, 'accuracy': 100},
    'Hi Jump Kick': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Horn Drill': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Hydro Pump': {'type': 'Water', 'category': 'Physical', 'effect': '', 'power': 110, 'accuracy': 80},
    'Hyper Beam': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 150, 'accuracy': 100},
    'Hyper Voice': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 90, 'accuracy': 100},
    'Hypnosis': {'type': 'Psychic', 'category': 'Status', 'effect': 'sleep', 'accuracy': 100},
    'Ice Beam': {'type': 'Ice', 'category': 'Physical', 'effect': '', 'power': 90, 'accuracy': 100, 'status': 'freeze', 'status_chance': 10},
    'Ice Punch': {'type': 'Ice', 'category': 'Physical', 'effect': '', 'power': 75, 'accuracy': 100},
    'Icy Wind': {'type': 'Ice', 'category': 'Physical', 'effect': '', 'power': 55, 'accuracy': 100},
    'Ingrain': {'type': 'Grass', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Iron Tail': {'type': 'Steel', 'category': 'Physical', 'effect': '', 'power': 100, 'accuracy': 75, 'status': 'def_down', 'status_chance': 30},
    'Knock Off': {'type': 'Dark', 'category': 'Physical', 'effect': '', 'power': 65, 'accuracy': 100},
    'Leaf Blade': {'type': 'Grass', 'category': 'Physical', 'effect': '', 'power': 90, 'accuracy': 100},
    'Leech Seed': {'type': 'Grass', 'category': 'Status', 'effect': 'leech', 'accuracy': 100},
    'Light Screen': {'type': 'Psychic', 'category': 'Status', 'effect': 'spd_wall', 'accuracy': 100},
    'Lovely Kiss': {'type': 'Normal', 'category': 'Status', 'effect': 'sleep', 'accuracy': 100},
    'Luster Purge': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'power': 70, 'accuracy': 100},
    'Mach Punch': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 40, 'accuracy': 100},
    'Magical Leaf': {'type': 'Grass', 'category': 'Physical', 'effect': '', 'power': 60, 'accuracy': 100},
    'Mean Look': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Mega Kick': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 120, 'accuracy': 100},
    'Megahorn': {'type': 'Bug', 'category': 'Physical', 'effect': '', 'power': 120, 'accuracy': 100},
    'Memento': {'type': 'Dark', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Metal Claw': {'type': 'Steel', 'category': 'Physical', 'effect': '', 'power': 50, 'accuracy': 100},
    'Meteor Mash': {'type': 'Steel', 'category': 'Physical', 'effect': '', 'power': 90, 'accuracy': 100},
    'Metronome': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Milk Drink': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Minimize': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Mirror Coat': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Mist Ball': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'power': 70, 'accuracy': 100},
    'Moonlight': {'type': 'Normal', 'category': 'Status', 'effect': 'heal', 'accuracy': 100},
    'Mud-Slap': {'type': 'Ground', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Night Shade': {'type': 'Ghost', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Nightmare': {'type': 'Ghost', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Outrage': {'type': 'Dragon', 'category': 'Physical', 'effect': '', 'power': 120, 'accuracy': 100},
    'Overheat': {'type': 'Fire', 'category': 'Physical', 'effect': '', 'power': 130, 'accuracy': 100},
    'Pain Split': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Perish Song': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Petal Dance': {'type': 'Grass', 'category': 'Physical', 'effect': '', 'power': 120, 'accuracy': 100},
    'Protect': {'type': 'Normal', 'category': 'Status', 'effect': 'protect', 'accuracy': 100},
    'Psych Up': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Psychic': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'power': 90, 'accuracy': 100, 'status': 'spa_down', 'status_chance': 10},
    'Pursuit': {'type': 'Dark', 'category': 'Physical', 'effect': '', 'power': 40, 'accuracy': 100},
    'Quick Attack': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 40, 'accuracy': 100},
    'Rain Dance': {'type': 'Water', 'category': 'Status', 'effect': 'rain', 'accuracy': 100},
    'Recover': {'type': 'Normal', 'category': 'Status', 'effect': 'heal', 'accuracy': 100},
    'Reflect': {'type': 'Psychic', 'category': 'Status', 'effect': 'def_wall', 'accuracy': 100},
    'Refresh': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Rest': {'type': 'Normal', 'category': 'Status', 'effect': 'heal', 'accuracy': 100},
    'Return': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Revenge': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 60, 'accuracy': 100},
    'Reversal': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Roar': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Rock Slide': {'type': 'Rock', 'category': 'Physical', 'effect': '', 'power': 75, 'accuracy': 90, 'status': 'flinch', 'status_chance': 30},
    'Rock Tomb': {'type': 'Rock', 'category': 'Physical', 'effect': '', 'power': 60, 'accuracy': 100},
    'Rollout': {'type': 'Rock', 'category': 'Physical', 'effect': '', 'power': 30, 'accuracy': 100},
    'Safeguard': {'type': 'Normal', 'category': 'Status', 'effect': 'status_block', 'accuracy': 100},
    'Sand Tomb': {'type': 'Ground', 'category': 'Physical', 'effect': '', 'power': 35, 'accuracy': 100},
    'Sand-Attack': {'type': 'Ground', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Sandstorm': {'type': 'Rock', 'category': 'Status', 'effect': 'sandstorm', 'accuracy': 100},
    'Scary Face': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Screech': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Secret Power': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 70, 'accuracy': 100},
    'Seismic Toss': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Shadow Ball': {'type': 'Ghost', 'category': 'Physical', 'effect': '', 'power': 80, 'accuracy': 100, 'status': 'spd_down', 'status_chance': 20},
    'Sheer Cold': {'type': 'Ice', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Signal Beam': {'type': 'Bug', 'category': 'Physical', 'effect': '', 'power': 75, 'accuracy': 100},
    'Silver Wind': {'type': 'Bug', 'category': 'Physical', 'effect': '', 'power': 60, 'accuracy': 100},
    'Sing': {'type': 'Normal', 'category': 'Status', 'effect': 'sleep', 'accuracy': 100},
    'Skill Swap': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Sky Attack': {'type': 'Flying', 'category': 'Physical', 'effect': '', 'power': 140, 'accuracy': 100},
    'Sky Uppercut': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 85, 'accuracy': 100},
    'Slash': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 70, 'accuracy': 100},
    'Sleep Powder': {'type': 'Grass', 'category': 'Status', 'effect': 'sleep', 'accuracy': 100},
    'Sleep Talk': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Sludge Bomb': {'type': 'Poison', 'category': 'Physical', 'effect': '', 'power': 90, 'accuracy': 100, 'status': 'poisoned', 'status_chance': 30},
    'SmellingSalt': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'SmokeScreen': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Softboiled': {'type': 'Normal', 'category': 'Status', 'effect': 'heal', 'accuracy': 100},
    'SolarBeam': {'type': 'Grass', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Spark': {'type': 'Electric', 'category': 'Physical', 'effect': '', 'power': 65, 'accuracy': 100},
    'Spikes': {'type': 'Ground', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Spore': {'type': 'Grass', 'category': 'Status', 'effect': 'sleep', 'accuracy': 100},
    'Steel Wing': {'type': 'Steel', 'category': 'Physical', 'effect': '', 'power': 70, 'accuracy': 100},
    'Stun Spore': {'type': 'Grass', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Substitute': {'type': 'Normal', 'category': 'Status', 'effect': 'substitute', 'accuracy': 100},
    'Sunny Day': {'type': 'Fire', 'category': 'Status', 'effect': 'sun', 'accuracy': 100},
    'Superpower': {'type': 'Fighting', 'category': 'Physical', 'effect': '', 'power': 120, 'accuracy': 100},
    'Surf': {'type': 'Water', 'category': 'Physical', 'effect': '', 'power': 90, 'accuracy': 100},
    'Swagger': {'type': 'Normal', 'category': 'Status', 'effect': 'confuse', 'accuracy': 100},
    'Sweet Scent': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Swift': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 60, 'accuracy': 100},
    'Swords Dance': {'type': 'Normal', 'category': 'Status', 'effect': 'atk_up', 'accuracy': 100},
    'Synthesis': {'type': 'Grass', 'category': 'Status', 'effect': 'heal', 'accuracy': 100},
    'Thrash': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 120, 'accuracy': 100},
    'Thunder': {'type': 'Electric', 'category': 'Physical', 'effect': '', 'power': 110, 'accuracy': 70, 'status': 'paralyzed', 'status_chance': 30},
    'Thunder Wave': {'type': 'Electric', 'category': 'Status', 'effect': 'paralyze', 'accuracy': 100},
    'ThunderPunch': {'type': 'Electric', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Thunderbolt': {'type': 'Electric', 'category': 'Physical', 'effect': '', 'power': 90, 'accuracy': 100, 'status': 'paralyzed', 'status_chance': 10},
    'Torment': {'type': 'Dark', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Toxic': {'type': 'Poison', 'category': 'Status', 'effect': 'toxic', 'accuracy': 100},
    'Tri Attack': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 80, 'accuracy': 100},
    'Trick': {'type': 'Psychic', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Water Pulse': {'type': 'Water', 'category': 'Physical', 'effect': '', 'power': 60, 'accuracy': 100},
    'Will-O-Wisp': {'type': 'Fire', 'category': 'Status', 'effect': 'burn', 'accuracy': 100},
    'Wish': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'accuracy': 100},
    'Wrap': {'type': 'Normal', 'category': 'Physical', 'effect': '', 'power': 15, 'accuracy': 100},
    'Yawn': {'type': 'Normal', 'category': 'Status', 'effect': 'sleep_next_turn', 'accuracy': 100},
    'Zap Cannon': {'type': 'Electric', 'category': 'Physical', 'effect': '', 'power': 120, 'accuracy': 50},
}
